### ISSUE TITLE
技术选型有问题。

### ISSUE THREAD

**Issue by rotencode** [Cyinx/einx#1]
gopher lua并不适合在这种项目中使用，其并没有支持c extended lib。

多个项目经验表明，无论是skynet还是其他静态+脚本的方案都是不适合用来做快速开发的。

**Comment by Cyinx** [comment]
einx并没有强行要求使用者去用lua，lua只是作为一个组件存在，你可以用他来写逻辑，也可以仅仅作为配置脚本，也可以一点lua都不用，只使用golang。一千个读者眼中有一千个哈姆雷特，所以我提供的仅仅是一个服务器手脚架，而不是一个格式固定的框架。
