### ISSUE TITLE
无法使用go get命令安装

### ISSUE THREAD

**Issue by lhwcd** [Cyinx/einx#2]
感谢开源此server，但是请在readme中提供go get安装方式，这样使用起来比较方便，也能解决包依赖问题

**Comment by Cyinx** [comment]
go get github.com/Cyinx/protobuf
go get github.com/go-sql-driver/mysql
go get github.com/yuin/gopher-lua
go get github.com/Cyinx/einx

按这个顺序安装试试。
其实protobuf要用我修改过的，因为我增加了自动生成newXXX的函数
